<a href="https://colab.research.google.com/github/MamaMoh/Machine-Learning/blob/main/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import scipy as sp

In [2]:
m = np.array([[1,5,2],[4,7,4],[2,0,9]])

In [3]:
eigen_vals, eign_vecs = np.linalg.eig(m)

In [5]:
print(eigen_vals,"\n")
print(eign_vecs,"\n")

[-1.32455532 11.32455532  7.        ] 

[[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]] 



In [7]:
nums = np.random.randint(1,20,size=(1,15))[0]
print("data: ",nums)

data:  [12 19  7 18 12 11  8  3 18  6 12 12  9  5  7]


In [11]:
print("Mean: ", sp.mean(nums))
print("Mean:", np.mean(nums))


Mean:  10.6
Mean: 10.6


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  """Entry point for launching an IPython kernel.


mode:  22.239999999999995
